name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'

    - name: Verify dependencies
      run: |
        go mod verify
        go mod tidy -v 

    - name: Install dependencies
      run: go mod download
      
    - name: Go vet
      run: go vet .

    - name: Build
      run: go build -v .


    

