name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod download

    - name: Build validation tools
      run: cd validation && go build -o validation.bin .

    - name: Run printf validation tests
      run: cd validation && ./validation.bin validate-printf
      # This will automatically fail the CI if the printf validation tests fail with exit code 1

    - name: Run errorf validation tests
      run: cd validation && ./validation.bin validate-errorf
      # This will test the Errorf functionality

    - name: Run benchmark comparison
      run: cd validation && ./validation.bin newbench
      # This runs the benchmarks but doesn't fail the build if the benchmarks are slower 