name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Explicitly declare permissions to address token-permissions security issue
permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd
        with:
          version: latest
          args: --timeout=5m --config=_lint/.production.golangci.json --skip-dirs=xprint_test
